### ISSUE TITLE
Create tags for all production workflows

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#234]
## Wait list
- [x] Wait for umccr/cwl-ica#231 
- [x] Wait for umccr/cwl-ica#232 
- [x] Wait for umccr/cwl-ica#233
- [x] Wait for umccr/cwl-ica#245 
- [x] Wait for umccr/cwl-ica#247 
  - [x] Related umccr/cwl-ica#248 
  - [x] Related umccr/cwl-ica#249
- [x] Wait for umccr/cwl-ica-cli#120 
- [x] Wait for umccr/cwl-ica-cli#126
- [x] Wait for umccr/cwl-ica#256
- [x] Wait for umccr/cwl-ica-cli#125
- [x] Wait for umccr/cwl-ica#264

## Workflows to make tags for
- [x] bclconvert
- [x] dragen-somatic
- [x] dragen-somatic+germline
- [x] dragen-germline
- [x] dragen-transcriptome  
    - [x] (needs to wait for umccr/cwl-ica#268)
    - [x] (needs to wait for umccr/cwl-ica#281) 
- [x] dragen-alignment
- [x] dragen tso 
- [x] rnasum
- [x] umccrise

**Comment by alexiswl** [comment]
Done, finally!
