### ISSUE TITLE
Fix TypeScript wiki before upcoming conference 

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#288]
Conference is at 4pm today lol.  

## TODO

- [x] Ensure TOC is up to date (do this last)

### Why typescript 

- [x] Fix typos / grammar errors in the https://github.com/umccr/cwl-ica/wiki/TypeScript#why-typescript section
- [x] 'guarantees' should be 'improves'
- [x] Mention cwlts repo here

### Initialising the TypeScript directory 

- [x] Add cwlts to required source packages
- [x] Add _node_modules_ to recommended patters to ignore in .gitignore
- [x] Explain the inputs and outputs in https://github.com/umccr/cwl-ica/wiki/TypeScript#initialise-the-function
- [x] Link to jetbrains tutorial for overriding filetypes for "overriding the cwljs file"

### Compile the Typescript
- [x] Rename to transpile from typescript to js 
- [x] Fix grammatical error: _command to temporarily populate install the package.json requirements_ and convert these to dot points.
- [x] Update link to cwl_ica_bin_dir 

### Configure your IDE section

- [x] Should add cwlts to package json here https://github.com/umccr/cwl-ica/wiki/TypeScript#step-2-add-a-packagejson-to-the-top-of-your-git-repo 
- [x] Update the step 1 to ensure user knows that they need to run those commands manually if they're not running cwl-ica installation script 
	- [x] Reference the https://github.com/umccr/cwl-ica/wiki/TypeScript#package-management-with-yarn for this
- [x] VSCode Users link is broken in the https://github.com/umccr/cwl-ica/wiki/TypeScript#webstorm-users section
